/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcon';

  static const IconData shop = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData wang = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData cartfill = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData homefill = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData my = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData myfill = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData goodsfavor = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData shoplight = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData home_light = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData my_light = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData cart_light = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData home_fill_light = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData cart_fill_light = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData favor_light = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData my_fill_light = const IconData(0xe810, fontFamily: _kFontFam);
}
